apiVersion: v1
kind: Service
metadata:
  name: devops-practice-service
  labels:
    app: devops-practice-service
  annotations:
    networking.gke.io/load-balancer-type: "External"
spec:
  ports:
    - port: 5000
      targetPort: 3000
  selector:
    app: devops-practice
    tier: devops-practice
  type: LoadBalancer